### ISSUE TITLE
Better error output for parse errors

### ISSUE THREAD

**Issue by rrdelaney** [ReasonablyTyped/ReasonablyTyped#43]
Right now the parse errors are really bad:

```
Error: Parse_error.Error: undefined
    at Object.compile (/usr/local/lib/node_modules/reasonably-typed/lib/index.js:45:11)
    at fs.readFile (/usr/local/lib/node_modules/reasonably-typed/lib/cli.js:86:40)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3)
```

We should make this better. I'm thinking something like the codeframe errors we do now for Modulegen errors.

**Comment by kogai** [comment]
I'd like to tackle this, please?

**Comment by rrdelaney** [comment]
Go for it 😁 feel free to PM me on discord if you need any help!
